# voracity mysql db service, version 1.0.0
FROM mysql:5.6
COPY ./my.cnf /etc/mysql/conf.d/
MAINTAINER Denys Sedchenko <dsedchenko@llnw.com>

ENV MYSQL_DATABASE=voracity \
MYSQL_ROOT_PASSWORD=wh3r315myc00k135

EXPOSE 3306
